In [1]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

In [2]:
X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

In [3]:
l=SVC(C=1e5,kernel='linear')
l.fit(X,y)

SVC(C=100000.0, kernel='linear')

In [4]:
print('w= ',l.coef_)
print('b= ',l.intercept_)
print('Indices of support vectors= ',l.support_)
print('Support vectors= ',l.support_vectors_)
print('No. of support vectors from each class= ',l.n_support_)
print('coefficient of support vectors in decision function= ',np.abs(l.dual_coef_))

w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors=  [2 3]
Support vectors=  [[ 2.  3.]
 [ 6. -1.]]
No. of support vectors from each class=  [1 1]
coefficient of support vectors in decision function=  [[0.0625 0.0625]]


In [5]:
import pandas as pd

In [6]:
data=pd.read_csv('/home/ise/Documents/sahana/glass.csv')
data.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [7]:
x=data.drop('Type',axis=1)
y=data.Type

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)


In [9]:
linear=svm.SVC(kernel='linear')
linear.fit(x_train,y_train)

SVC(kernel='linear')

In [10]:
print(linear.support_vectors_)

[[ 1.52196 14.36     3.85    ...  9.15     0.       0.     ]
 [ 1.51764 12.98     3.54    ...  8.53     0.       0.     ]
 [ 1.51721 12.87     3.48    ...  8.43     0.       0.     ]
 ...
 [ 1.51617 14.95     0.      ...  8.71     0.67     0.     ]
 [ 1.5164  14.37     0.      ...  9.45     0.54     0.     ]
 [ 1.51831 14.39     0.      ...  6.47     2.88     0.     ]]


In [11]:
print(linear.n_support_)

[41 47 13  9  6  8]


In [12]:
y_pred=linear.predict(x_test)

In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.676923076923077


In [14]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[14  6  0  0  0  0]
 [ 5 18  0  0  2  0]
 [ 2  2  0  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  2  0]
 [ 2  0  0  1  1  8]]


In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.61      0.70      0.65        20
           2       0.69      0.72      0.71        25
           3       0.00      0.00      0.00         4
           5       0.67      1.00      0.80         2
           6       0.40      1.00      0.57         2
           7       1.00      0.67      0.80        12

    accuracy                           0.68        65
   macro avg       0.56      0.68      0.59        65
weighted avg       0.67      0.68      0.66        65



/home/ise/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ise/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ise/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [17]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)


SVC()

In [18]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [19]:
print("prediction by model1 ",accuracy_score(y_test,y_pred1))
print("prediction by model2",accuracy_score(y_test,y_pred2))
print("prediction by model3",accuracy_score(y_test,y_pred1))

prediction by model1  0.38461538461538464
prediction by model2 0.38461538461538464
prediction by model3 0.38461538461538464
